# Generated by Django 4.0.1 on 2023-11-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPP', '0002_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
