# Generated by Django 3.2.24 on 2024-04-19 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField()),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('BDate', models.CharField(default='', max_length=100)),
                ('Time', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField(max_length=100)),
                ('Length', models.FloatField(max_length=100)),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Saloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Ownername', models.CharField(max_length=100)),
                ('Phone', models.BigIntegerField()),
                ('Image', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Pin', models.CharField(default='', max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Servicename', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('Duration', models.IntegerField()),
                ('Price', models.FloatField()),
                ('SALOON', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.saloon')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=100)),
                ('Phone', models.BigIntegerField(default='')),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Pin', models.CharField(default='', max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Image', models.CharField(default='', max_length=250)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Servicescat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('SALOON', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.saloon')),
                ('SERVICES', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.services')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reportmsg', models.CharField(max_length=500)),
                ('Reporteddate', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('Reply', models.CharField(max_length=100)),
                ('SALOON', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.saloon')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Amount', models.FloatField()),
                ('BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.booking')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(default='', max_length=500)),
                ('License', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.BigIntegerField()),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Pin', models.CharField(default='', max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('Mandate', models.DateField()),
                ('Images', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
                ('Instock', models.CharField(max_length=100)),
                ('SALOON', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MyApp.saloon')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedbackmsg', models.CharField(max_length=100)),
                ('Date', models.CharField(default='', max_length=100)),
                ('SALOON', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.saloon')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Pin', models.CharField(default='', max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Image', models.CharField(max_length=100)),
                ('Qualification', models.CharField(default='', max_length=100)),
                ('SALOON', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.saloon')),
            ],
        ),
        migrations.CreateModel(
            name='Donationapprove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=100)),
                ('DONATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.donation')),
                ('SALOON', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MyApp.saloon')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='ORGANIZATION',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MyApp.organization'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SERVICE', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MyApp.services')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bookingsub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.booking')),
                ('SERVICES', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.services')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='SALOON',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MyApp.saloon'),
        ),
        migrations.AddField(
            model_name='booking',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.user'),
        ),
    ]
