# Generated by Django 3.2.24 on 2024-04-19 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicescat',
            name='SERVICES',
        ),
        migrations.AddField(
            model_name='services',
            name='SERVICESCAT',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MyApp.servicescat'),
        ),
    ]
