# Generated by Django 3.2.24 on 2024-04-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20240419_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='Token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
