# Generated by Django 3.2.24 on 2024-04-23 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_services_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='Token',
        ),
    ]
