# Generated by Django 3.2.24 on 2024-04-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_remove_services_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
