# Generated by Django 3.2.24 on 2024-04-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_booking_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='BDate',
            field=models.DateField(),
        ),
    ]
